nouveau_xv: fix missing include of extinit.h
> nouveau_xv.c: In function 'NVSetupOverlayVideo':
> nouveau_xv.c:1973:14: error: 'noCompositeExtension' undeclared (first use in this function)
>  1973 |         if (!noCompositeExtension) {

Signed-off-by: Enrico Weigelt, metux IT consult <info@metux.net>