wfb: Fix missing init function decls behind FB_ACCESS_WRAPPER
Fixes warning with xserver 1.20 and gcc 8.2:

nv_driver.c:1443:9: warning: implicit declaration of function ‘wfbScreenInit’; did you mean ‘fbScreenInit’? [-Wimplicit-function-declaration]
   ret = wfbScreenInit(pScreen, FBStart, pScrn->virtualX,
         ^~~~~~~~~~~~~
         fbScreenInit

(See xserver 706e6d9cd074da606016ed4ecff51e9c2a822087)

Signed-off-by: Rhys Kidd <rhyskidd@gmail.com>